import type { Metadata } from 'next';
import './globals.css';
import { siteConfig } from '@config/siteConfig';

export const metadata: Metadata = {
    title: siteConfig.siteName,
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="me"
                    href="https://gts.endgameviable.com/@ultrviolet"
                />
                <link rel="me" href="https://github.com/endgameviable" />
                <link
                    rel="webmention"
                    href="https://webmention.io/beta.endgameviable.com/webmention"
                />
            </head>
            <body>{children}</body>
        </html>
    );
}
